name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Get version and package name
        id: version
        run: |
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT

      - name: Upload release tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.version.outputs.name }}-${{ steps.version.outputs.version }}
          path: ${{ steps.version.outputs.name }}-${{ steps.version.outputs.version }}.tar.gz
          retention-days: 30

      - name: Upload build debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-${{ steps.version.outputs.version }}
          path: |
            build/
            package.json
            package-lock.json
            README.md
            icon.png
          retention-days: 30
